import { createFileRoute } from "@tanstack/react-router";
import { Check, Copy, Pencil, RefreshCw } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/signal/AppShell";
import { Button } from "@/components/signal/Button";
import { PageHeader, Panel } from "@/components/signal/PageHeader";
import { outputs } from "@/components/signal/data";

export const Route = createFileRoute("/content-studio")({ head: () => ({ meta: [{ title: "Content Studio — Signal Splitter" }, { name: "description", content: "Create accurate platform-specific social content from one verified source." }, { property: "og:title", content: "Content Studio — Signal Splitter" }, { property: "og:description", content: "Generate LinkedIn, X, Instagram and short-video content without factual drift." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ContentStudio });
type Platform = keyof typeof outputs;
function ContentStudio(){ const [active,setActive]=useState<Platform>("LinkedIn"); const [editing,setEditing]=useState(false); const [text,setText]=useState(outputs); const [copied,setCopied]=useState(false); const copy=async()=>{await navigator.clipboard.writeText(text[active]);setCopied(true);setTimeout(()=>setCopied(false),1200)}; const regen=()=>setText(v=>({...v,[active]:outputs[active]+"\n\nReady for editorial review."})); return <AppShell><PageHeader eyebrow="Content studio" title="Shape the signal for every platform." description="Each draft follows the conventions of its channel while staying tied to the same verified source." />
<Panel><div className="flex overflow-x-auto border-b border-ink/10 pb-3">{(Object.keys(outputs) as Platform[]).map(tab=><button key={tab} onClick={()=>{setActive(tab);setEditing(false)}} className={`shrink-0 rounded-lg px-3 py-2 text-sm font-medium transition ${active===tab?"bg-ink text-paper":"text-ink/55 hover:bg-panel/70 hover:text-ink"}`}>{tab}</button>)}</div><div className="mt-5 rounded-lg bg-panel/75 p-5 ring-1 ring-ink/5"><div className="flex items-center justify-between"><p className="eyebrow">Generated content</p><span className="rounded bg-brand/10 px-2 py-1 font-mono text-[10px] text-brand">FACT LOCKED</span></div>{editing?<textarea value={text[active]} onChange={e=>setText(v=>({...v,[active]:e.target.value}))} className="mt-4 min-h-72 w-full resize-y bg-transparent text-sm leading-7 text-ink/80 outline-none" />:<p className="mt-4 min-h-72 whitespace-pre-line text-sm leading-7 text-ink/80">{text[active]}</p>}<div className="mt-5 flex flex-wrap items-center gap-2 border-t border-ink/10 pt-4"><Button onClick={copy}>{copied?<Check className="size-4"/>:<Copy className="size-4"/>}{copied?"Copied":"Copy"}</Button><Button onClick={()=>setEditing(v=>!v)}><Pencil className="size-4" />{editing?"Save":"Edit"}</Button><Button className="sm:ml-auto" onClick={regen}><RefreshCw className="size-4" />Regenerate</Button></div></div></Panel></AppShell> }
