import { createFileRoute } from "@tanstack/react-router";
import { AlertTriangle, CheckCircle2, CircleX, FileWarning } from "lucide-react";
import { AppShell } from "@/components/signal/AppShell";
import { PageHeader, Panel } from "@/components/signal/PageHeader";
import { claims } from "@/components/signal/data";

export const Route = createFileRoute("/fact-lock")({ head: () => ({ meta: [{ title: "Fact Lock — Signal Splitter" }, { name: "description", content: "Review generated claims against supporting source evidence." }, { property: "og:title", content: "Fact Lock — Signal Splitter" }, { property: "og:description", content: "Trace every generated claim to its source evidence and review warnings." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: FactLock });
const styles={"Supported":{icon:CheckCircle2,cls:"text-brand bg-brand/10"},"Altered":{icon:FileWarning,cls:"text-amber bg-amber/10"},"Unsupported":{icon:CircleX,cls:"text-rose bg-rose/10"},"Context Warning":{icon:AlertTriangle,cls:"text-signal bg-signal/10"}} as const;
function FactLock(){return <AppShell><PageHeader eyebrow="Evidence register" title="Every claim, traced back to source." description="Review supported statements, altered facts, unsupported additions and missing context before anything ships." action={<div className="rounded-lg bg-panel/60 px-4 py-3 ring-1 ring-ink/5"><p className="eyebrow">Claim integrity</p><p className="mt-1 font-mono text-2xl font-semibold">1 / 4 <span className="text-sm text-ink/45">needs action</span></p></div>} /><div className="space-y-4">{claims.map((item,i)=>{const s=styles[item.status];const Icon=s.icon;return <Panel key={item.claim}><div className="grid gap-5 lg:grid-cols-[1.1fr_1fr]"><div><div className="flex flex-wrap items-center gap-3"><span className={`inline-flex items-center gap-1.5 rounded px-2 py-1 text-[10px] font-semibold uppercase ${s.cls}`}><Icon className="size-3" />{item.status}</span><span className="font-mono text-[10px] text-ink/35">CLAIM {String(i+1).padStart(2,"0")}</span></div><h2 className="mt-4 text-base font-semibold leading-relaxed">{item.claim}</h2><p className="mt-3 text-sm leading-relaxed text-ink/55">{item.explanation}</p></div><blockquote className="rounded-lg border-l-2 border-brand bg-panel/65 p-4"><p className="eyebrow">Supporting source passage</p><p className="mt-3 text-sm italic leading-6 text-ink/65">“{item.passage}”</p><p className="mt-3 font-mono text-[10px] text-ink/35">SOURCE ¶ {i+2}:1{i+3}</p></blockquote></div></Panel>})}</div></AppShell>}
