import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { AppShell } from "@/components/signal/AppShell";
import { Button } from "@/components/signal/Button";
import { PageHeader, Panel } from "@/components/signal/PageHeader";
import { QualityBars } from "@/components/signal/QualityBars";

export const Route = createFileRoute("/quality-check")({ head: () => ({ meta: [{ title: "Quality Check — Signal Splitter" }, { name: "description", content: "Score content for factual consistency, coverage, brand alignment and platform fit." }, { property: "og:title", content: "Quality Check — Signal Splitter" }, { property: "og:description", content: "A clear pre-publish quality report for every generated platform output." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: QualityCheck });
function QualityCheck(){return <AppShell><PageHeader eyebrow="Preflight review" title="A final check before the signal goes live." description="See where the content is strong and what needs attention across accuracy, source use, brand voice and platform conventions." action={<div className="rounded-lg bg-brand/10 px-4 py-3 ring-1 ring-brand/20"><div className="flex items-center gap-2 text-brand"><CheckCircle2 className="size-4"/><span className="text-sm font-semibold">Ready with review</span></div><p className="mt-1 text-xs text-ink/50">Overall quality score: 92%</p></div>} /><div className="grid gap-6 xl:grid-cols-[1fr_360px]"><Panel><p className="eyebrow">Quality indicators</p><div className="mt-6"><QualityBars detailed /></div></Panel><div className="space-y-4"><Panel><p className="eyebrow">Review summary</p><ul className="mt-4 space-y-4 text-sm text-ink/65"><li className="flex gap-3"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-brand"/>All primary statistics remain true to the source.</li><li className="flex gap-3"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-signal"/>Six of seven key ideas are represented across outputs.</li><li className="flex gap-3"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-amber"/>X thread could use a clearer source qualifier.</li></ul></Panel><Panel><p className="eyebrow">Next action</p><p className="mt-3 text-sm leading-relaxed text-ink/60">Review the context warning, then return to the studio for final edits.</p><Link to="/fact-lock" className="mt-4 inline-block"><Button variant="primary">Review Fact Lock <ArrowRight className="size-4"/></Button></Link></Panel></div></div></AppShell>}
